# Generated by Django 4.2 on 2025-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
